"""Add ix_projects_client_id index

Revision ID: 370af72fb83e
Revises: dae8278db9b1
Create Date: 2026-09-18 18:09:55.791413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370af72fb83e'
down_revision: Union[str, None] = 'dae8278db9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_projects_client_id', 'projects', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_client_id', table_name='projects')
    # ### end Alembic commands ###
