"""001_initial_schema

Revision ID: dae8278db9b1
Revises: 
Create Date: 2026-06-17 22:41:18.369626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dae8278db9b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_company'), 'clients', ['company'], unique=False)
    op.create_index(op.f('ix_clients_created_at'), 'clients', ['created_at'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_updated_at'), 'clients', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'viewer', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='projectstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='projectpriority'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_projects_code', 'projects', ['code'], unique=False)
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index('ix_projects_created_by', 'projects', ['created_by'], unique=False)
    op.create_index('ix_projects_priority', 'projects', ['priority'], unique=False)
    op.create_index('ix_projects_status_created_at', 'projects', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_projects_updated_at'), 'projects', ['updated_at'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'blocked', 'done', name='storystatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='storypriority'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stories_assigned_to_status', 'stories', ['assigned_to', 'status'], unique=False)
    op.create_index(op.f('ix_stories_created_at'), 'stories', ['created_at'], unique=False)
    op.create_index('ix_stories_created_by', 'stories', ['created_by'], unique=False)
    op.create_index('ix_stories_project_id_created_at', 'stories', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_stories_status_priority', 'stories', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_stories_updated_at'), 'stories', ['updated_at'], unique=False)
    op.create_table('story_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'applied', name='draftstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_drafts_created_at'), 'story_drafts', ['created_at'], unique=False)
    op.create_index('ix_story_drafts_created_by_status', 'story_drafts', ['created_by', 'status'], unique=False)
    op.create_index('ix_story_drafts_project_id_created_at', 'story_drafts', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_story_drafts_status', 'story_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_story_drafts_updated_at'), 'story_drafts', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_index(op.f('ix_story_drafts_updated_at'), table_name='story_drafts')
    op.drop_index('ix_story_drafts_status', table_name='story_drafts')
    op.drop_index('ix_story_drafts_project_id_created_at', table_name='story_drafts')
    op.drop_index('ix_story_drafts_created_by_status', table_name='story_drafts')
    op.drop_index(op.f('ix_story_drafts_created_at'), table_name='story_drafts')
    op.drop_table('story_drafts')
    op.drop_index(op.f('ix_stories_updated_at'), table_name='stories')
    op.drop_index('ix_stories_status_priority', table_name='stories')
    op.drop_index('ix_stories_project_id_created_at', table_name='stories')
    op.drop_index('ix_stories_created_by', table_name='stories')
    op.drop_index(op.f('ix_stories_created_at'), table_name='stories')
    op.drop_index('ix_stories_assigned_to_status', table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_projects_updated_at'), table_name='projects')
    op.drop_index('ix_projects_status_created_at', table_name='projects')
    op.drop_index('ix_projects_priority', table_name='projects')
    op.drop_index('ix_projects_created_by', table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_index('ix_projects_code', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_updated_at'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_created_at'), table_name='clients')
    op.drop_index(op.f('ix_clients_company'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###

    # PostgreSQL ENUM types are separate DB objects from the columns/tables
    # that use them — op.drop_table() does NOT drop them, so they must be
    # dropped explicitly or a downgrade -> upgrade cycle fails on the
    # subsequent CREATE TYPE with a DuplicateObjectError.
    postgresql.ENUM(name='draftstatus').drop(bind, checkfirst=True)
    postgresql.ENUM(name='storypriority').drop(bind, checkfirst=True)
    postgresql.ENUM(name='storystatus').drop(bind, checkfirst=True)
    postgresql.ENUM(name='projectpriority').drop(bind, checkfirst=True)
    postgresql.ENUM(name='projectstatus').drop(bind, checkfirst=True)
    postgresql.ENUM(name='userrole').drop(bind, checkfirst=True)
