app:
  name: App API
  version: 1.0.0

jwt:
  secret_key: !ENV ${SECRET_KEY}
  algorithm: HS256
  access_token_expire_minutes: 1440

persistence:
  driver: in-memory

logging:
  level: WARNING
  format: text
  outputs:
  - type: console
