app:
  name: "App API"
  version: "1.0.0"

jwt:
  secret_key: !ENV ${SECRET_KEY}
  algorithm: "HS256"
  access_token_expire_minutes: 480

cors:
  origins:
    - !ENV ${CORS_ORIGINS}
  allow_credentials: !ENV ${CORS_ALLOW_CREDENTIALS:false}
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Authorization"
    - "Content-Type"
    - "Accept"

postgres:
  username: !ENV ${POSTGRES_USER:open-projects-hub-admin}
  password: !ENV ${POSTGRES_PASSWORD}
  host: !ENV ${POSTGRES_HOST}
  port: !ENV ${POSTGRES_PORT:5432}
  dbname: !ENV ${POSTGRES_DB:open-projects-hub-db}
  echo: false  # SQLAlchemy echo logs
  pool_size: 10
  max_over_flow: 10
  pool_timeout: 30
