app:
  name: Open Projects Hub API
  version: 1.0.0

jwt:
  secret_key: !ENV ${SECRET_KEY}
  algorithm: HS256
  access_token_expire_minutes: 1440

persistence:
  driver: postgresql
  postgres:
    username: open-projects-hub-admin
    password: test_password
    host: localhost
    port: 5432
    dbname: open-projects-hub-db
    echo: false

logging:
  level: WARNING
  format: text
  outputs:
  - type: console

ai:
  provider: mock    # gemini | mock
  gemini_api_key: !ENV ${GEMINI_API_KEY}
  gemini_model: gemini-2.5-flash
